<a href="https://colab.research.google.com/github/sahal-mulki/learning-pytorch/blob/main/Part%201%20-%20Intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# My first notebook made while trying to learn PyTorch!

In [18]:
# CREATED IN PART USING THE GEMINI AI FUNCTION IN COLAB

!pip install --upgrade torch torchvision

ERROR: Operation cancelled by user


In [19]:
import torch

z = torch.zeros(2, 3)
print(z)
print("Z has the type:")
print(z.dtype)

ones = torch.ones((2, 3), dtype=torch.int16)

print("Ones has the type:")
print(ones.type)
print(ones)

torch.manual_seed(1234)
r1 = torch.rand((2, 2), dtype=torch.float16)
print('A random tensor:')
print(r1)

r2 = torch.rand((2, 2), dtype=torch.float16)
print('A different random tensor:')
print(r2)

torch.manual_seed(1234)
r3 = torch.rand((2, 2), dtype=torch.float16)
print('Should match r1:')
print(r3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
Z has the type:
torch.float32
Ones has the type:
<built-in method type of Tensor object at 0x791f9482d800>
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
A random tensor:
tensor([[0.3979, 0.3530],
        [0.6436, 0.5259]], dtype=torch.float16)
A different random tensor:
tensor([[0.5996, 0.6816],
        [0.3242, 0.9966]], dtype=torch.float16)
Should match r1:
tensor([[0.3979, 0.3530],
        [0.6436, 0.5259]], dtype=torch.float16)


In [21]:
ones = torch.ones((2, 3), dtype=torch.int16)
print(ones)

fours = torch.ones((2, 3), dtype=torch.int16) * 4
print(fours)

fives = ones + fours
print(fives)
print(fives.shape)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
tensor([[4, 4, 4],
        [4, 4, 4]], dtype=torch.int16)
tensor([[5, 5, 5],
        [5, 5, 5]], dtype=torch.int16)
torch.Size([2, 3])


pytorch seed changes everytime with new random call??

In [22]:
torch.seed()

17295900731922219800

In [23]:
fours = torch.ones((2, 3), dtype=torch.int16) * 4

In [25]:
r3 = r1 + r2

In [26]:
torch.seed()

85034306175053947

In [38]:
random_between_1_and_1 = torch.rand(2, 2) - 0.5 * 2
print(random_between_1_and_1)

print(torch.abs(random_between_1_and_1))

print(torch.asin(random_between_1_and_1))

print(torch.det(random_between_1_and_1))

print(torch.svd(random_between_1_and_1))

print(torch.std_mean(random_between_1_and_1))

print(torch.max(random_between_1_and_1))

tensor([[-0.4142, -0.7675],
        [-0.7479, -0.6860]])
tensor([[0.4142, 0.7675],
        [0.7479, 0.6860]])
tensor([[-0.4271, -0.8750],
        [-0.8450, -0.7560]])
tensor(-0.2899)
torch.return_types.svd(
U=tensor([[-0.6485, -0.7613],
        [-0.7613,  0.6485]]),
S=tensor([1.3200, 0.2196]),
V=tensor([[ 0.6348, -0.7727],
        [ 0.7727,  0.6348]]))
(tensor(0.1635), tensor(-0.6539))
tensor(-0.4142)


In [42]:
import torch.nn as nn
import torch.nn.functional as F

In [90]:
class MulkiNet(nn.Module):

    def __init__(self):
        super(MulkiNet, self).__init__()
        # 1 input image channel (black & white), 6 output channels, 8*8 square convolution
        # kernel
        self.conv1 = nn.Conv2d(1, 6, 8)
        self.conv2 = nn.Conv2d(6, 16, 4)
        # an affine operation: y = Wx + b
        self.fc1 = nn.Linear(16 * 4 * 4, 256)  # 4*4 from image dimension
        self.fc2 = nn.Linear(256, 64)
        self.fc3 = nn.Linear(64, 10)

    def forward(self, x):
        # Max pooling over a (2, 2) window
        x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
        # If the size is a square you can only specify a single number
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)
        x = x.view(-1, self.num_flat_features(x))
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

    def num_flat_features(self, x):
        size = x.size()[1:]  # all dimensions except the batch dimension
        num_features = 1
        for s in size:
            num_features *= s
        return num_features

class LeNet(nn.Module):

    def __init__(self):
        super(LeNet, self).__init__()
        # 1 input image channel (black & white), 6 output channels, 5x5 square convolution
        # kernel
        self.conv1 = nn.Conv2d(1, 6, 5)
        self.conv2 = nn.Conv2d(6, 16, 5)
        # an affine operation: y = Wx + b
        self.fc1 = nn.Linear(16 * 5 * 5, 120)  # 5*5 from image dimension
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)

    def forward(self, x):
        # Max pooling over a (2, 2) window
        x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
        # If the size is a square you can only specify a single number
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)
        x = x.view(-1, self.num_flat_features(x))
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

    def num_flat_features(self, x):
        size = x.size()[1:]  # all dimensions except the batch dimension
        num_features = 1
        for s in size:
            num_features *= s
        return num_features

In [91]:
net = MulkiNet()

print(net)

lenet = LeNet()

print(lenet)

MulkiNet(
  (conv1): Conv2d(1, 6, kernel_size=(8, 8), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(4, 4), stride=(1, 1))
  (fc1): Linear(in_features=256, out_features=256, bias=True)
  (fc2): Linear(in_features=256, out_features=64, bias=True)
  (fc3): Linear(in_features=64, out_features=10, bias=True)
)
LeNet(
  (conv1): Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear(in_features=400, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)


In [93]:
input = torch.rand(1, 1, 32, 32)   # stand-in for a 32x32 black & white image
print('Image batch shape:')
print(input.shape)

output = net(input)                # we don't call forward() directly
print('\nRaw output:')
print(output)
print(output.shape)

Image batch shape:
torch.Size([1, 1, 32, 32])

Raw output:
tensor([[ 0.0563,  0.0083, -0.0747, -0.0653,  0.0381,  0.0324, -0.1358,  0.0253,
         -0.0910, -0.0867]], grad_fn=<AddmmBackward0>)
torch.Size([1, 10])
