<a href="https://colab.research.google.com/github/sahal-mulki/learning-pytorch/blob/main/Part%202%20-%20Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Part 2 - Tensors

In [1]:
import torch, math

In [2]:
empty_tensor = torch.empty(3, 4)

print(empty_tensor)
print(type(empty_tensor))

tensor([[-1.6220e+37,  4.4631e-41,  1.3549e-09,  3.0766e-41],
        [-9.9587e+36,  4.4631e-41,  4.1759e-30,  4.4631e-41],
        [-5.0181e+36,  4.4631e-41, -9.4396e+36,  4.4631e-41]])
<class 'torch.Tensor'>


In [11]:
zeroes = torch.zeros((3,4), dtype=torch.float64)

ones = torch.ones(3, 4)

In [12]:
zeroes

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]], dtype=torch.float64)

In [13]:
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [29]:
torch.manual_seed(1729)

rando = torch.rand(2,3)

In [27]:
print(rando)

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])


In [22]:
rando = torch.rand(2,3)

In [35]:
torch.manual_seed(1729)

In [36]:
torch.seed()

16445031461178843550

In [37]:
x = torch.empty(2, 2, 3)

In [38]:
x

tensor([[[1.5766e-19, 1.0256e-08, 4.2004e-05],
         [3.1644e+12, 1.7341e-07, 1.7283e-04]],

        [[2.5643e-09, 1.2892e+16, 2.1707e-18],
         [7.0952e+22, 1.7748e+28, 1.8176e+31]]])

In [39]:
x.shape

torch.Size([2, 2, 3])

In [42]:
x[0][0][0]

tensor(1.5766e-19)

In [43]:
empty_like_x = torch.empty_like(x)
print(empty_like_x.shape)
print(empty_like_x)

zeros_like_x = torch.zeros_like(x)
print(zeros_like_x.shape)
print(zeros_like_x)

ones_like_x = torch.ones_like(x)
print(ones_like_x.shape)
print(ones_like_x)

rand_like_x = torch.rand_like(x)
print(rand_like_x.shape)
print(rand_like_x)

torch.Size([2, 2, 3])
tensor([[[6.4290e-09, 3.0766e-41, 6.0573e-09],
         [3.0766e-41, 1.1210e-43, 0.0000e+00]],

        [[8.9683e-44, 0.0000e+00, 9.6818e+27],
         [3.0770e-41, 1.0842e-19, 6.5099e-01]]])
torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])
tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])
torch.Size([2, 2, 3])
tensor([[[0.8559, 0.0156, 0.7691],
         [0.3985, 0.4853, 0.9381]],

        [[0.3754, 0.7733, 0.4887],
         [0.8013, 0.9687, 0.5173]]])


In [45]:
constants = torch.tensor([[3.1415926, 2.71828], [1.61803, 0]])
print(constants)

some_integers = torch.tensor((2, 3, 5, 7, 11, 13, 17, 19))
print(some_integers)

more_integers = torch.tensor(([2, 4, 6], [3, 6, 9]))
print(more_integers)

tensor([[3.1416, 2.7183],
        [1.6180, 0.0000]])
tensor([ 2,  3,  5,  7, 11, 13, 17, 19])
tensor([[2, 4, 6],
        [3, 6, 9]])


In [46]:
torch.tensor(more_integers)

<ipython-input-46-be8e34700a98>:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  torch.tensor(more_integers)


tensor([[2, 4, 6],
        [3, 6, 9]])

In [51]:
a = torch.rand((2, 3), dtype=torch.float16) * 20
print(a)

c = a.to(torch.int32)
print(c)

tensor([[ 9.8750,  5.6172,  2.3926],
        [ 2.8711, 16.5000, 18.9688]], dtype=torch.float16)
tensor([[ 9,  5,  2],
        [ 2, 16, 18]], dtype=torch.int32)


In [61]:
c[0][0] += 1

In [70]:
c

tensor([[ 3,  5,  2],
        [ 2, 16, 18]], dtype=torch.int32)

In [69]:
c + c

tensor([[ 6, 10,  4],
        [ 4, 32, 36]], dtype=torch.int32)

In [71]:
c = c.to(torch.float32)

In [72]:
torch.sin_(c)

tensor([[ 0.1411, -0.9589,  0.9093],
        [ 0.9093, -0.2879, -0.7510]])

In [73]:
c

tensor([[ 0.1411, -0.9589,  0.9093],
        [ 0.9093, -0.2879, -0.7510]])

In [76]:
c.add_(ones_like_x[0])

tensor([[1.1411, 0.0411, 1.9093],
        [1.9093, 0.7121, 0.2490]])

In [77]:
c

tensor([[1.1411, 0.0411, 1.9093],
        [1.9093, 0.7121, 0.2490]])

In [79]:
d = c.clone()

In [80]:
assert d is not c

In [81]:
c.unsqueeze_(0)

tensor([[[1.1411, 0.0411, 1.9093],
         [1.9093, 0.7121, 0.2490]]])

In [82]:
c

tensor([[[1.1411, 0.0411, 1.9093],
         [1.9093, 0.7121, 0.2490]]])

In [87]:
c[0].add_((d))

tensor([[2.2822, 0.0822, 3.8186],
        [3.8186, 1.4242, 0.4980]])

In [88]:
c

tensor([[[2.2822, 0.0822, 3.8186],
         [3.8186, 1.4242, 0.4980]]])

In [92]:
c = torch.rand(2, 2)

In [93]:
d = c.numpy()

In [94]:
d

array([[0.9828484 , 0.40637296],
       [0.6507735 , 0.83319443]], dtype=float32)

In [95]:
c = torch.rand(2, 2)

In [96]:
d

array([[0.9828484 , 0.40637296],
       [0.6507735 , 0.83319443]], dtype=float32)