<a href="https://colab.research.google.com/github/sahal-mulki/learning-pytorch/blob/main/Part%201%20-%20Intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# My first notebook made while trying to learn PyTorch!

In [18]:
# CREATED IN PART USING THE GEMINI AI FUNCTION IN COLAB

!pip install --upgrade torch torchvision

ERROR: Operation cancelled by user


In [19]:
import torch

z = torch.zeros(2, 3)
print(z)
print("Z has the type:")
print(z.dtype)

ones = torch.ones((2, 3), dtype=torch.int16)

print("Ones has the type:")
print(ones.type)
print(ones)

torch.manual_seed(1234)
r1 = torch.rand((2, 2), dtype=torch.float16)
print('A random tensor:')
print(r1)

r2 = torch.rand((2, 2), dtype=torch.float16)
print('A different random tensor:')
print(r2)

torch.manual_seed(1234)
r3 = torch.rand((2, 2), dtype=torch.float16)
print('Should match r1:')
print(r3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
Z has the type:
torch.float32
Ones has the type:
<built-in method type of Tensor object at 0x791f9482d800>
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
A random tensor:
tensor([[0.3979, 0.3530],
        [0.6436, 0.5259]], dtype=torch.float16)
A different random tensor:
tensor([[0.5996, 0.6816],
        [0.3242, 0.9966]], dtype=torch.float16)
Should match r1:
tensor([[0.3979, 0.3530],
        [0.6436, 0.5259]], dtype=torch.float16)


In [21]:
ones = torch.ones((2, 3), dtype=torch.int16)
print(ones)

fours = torch.ones((2, 3), dtype=torch.int16) * 4
print(fours)

fives = ones + fours
print(fives)
print(fives.shape)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
tensor([[4, 4, 4],
        [4, 4, 4]], dtype=torch.int16)
tensor([[5, 5, 5],
        [5, 5, 5]], dtype=torch.int16)
torch.Size([2, 3])
